version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file: .env
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./jfr:/app/jfr
      - ./arquivos:/app/arquivos
    environment:
      JAVA_TOOL_OPTIONS: "-XX:StartFlightRecording=duration=1h,filename=/app/jfr/app_recording.jfr,name=app,settings=profile"
    command: ["java", "-jar", "app.jar"]

volumes:
  pgdata:
  pgadmin_data:
