CREATE TABLE IF NOT EXISTS EMPRESAS (
    CODIGO	    SERIAL PRIMARY KEY,
    RAZAO_SOCIAL VARCHAR(255) NOT NULL,
	NOME_FANTASIA VARCHAR(255) NOT NULL,
	CNPJ VARCHAR(14) NOT NULL,
	UF CHAR(2) NOT NULL,
	IND_NIRE	NUMERIC(5) NOT NULL CHECK (IND_NIRE IN (0, 1))
);

CREATE TABLE IF NOT EXISTS PLANO_CONTAS (
    CODIGO	    SERIAL PRIMARY KEY,
    CONTA	    VARCHAR(50) NOT NULL,
	DESCRICAO	VARCHAR(255) NOT NULL,
    DT_INI  	DATE NOT NULL,
    DT_FIM	    DATE,
    TIPO  	    CHAR(1) CHECK (TIPO IN ('A', 'S')),
    CONTA_SUP   VARCHAR(50),
    NIVEL	    NUMERIC(5) NOT NULL,
    NATUREZA    NUMERIC(5) NOT NULL CHECK (NATUREZA IN (1, 2, 3, 4))
);

CREATE TABLE IF NOT EXISTS LANC_CONTABEIS (
    CODIGO	    SERIAL PRIMARY KEY,
    NUM_LCTO    NUMERIC(10) NOT NULL,
    DT_LCTO     DATE NOT NULL,
    VL_LCTO     NUMERIC(10, 2) NOT NULL,
    IND_DC      CHAR(1) CHECK (IND_DC IN ('D', 'C')),
    COD_CTA     SERIAL NOT NULL,
    CONSTRAINT FK_LANC_CONTABEIS_COD_CTA FOREIGN KEY(COD_CTA) REFERENCES PLANO_CONTAS(CODIGO),
    COD_EMP     SERIAL NOT NULL,
    CONSTRAINT FK_LANC_CONTABEIS_COD_EMP FOREIGN KEY(COD_EMP) REFERENCES EMPRESAS(CODIGO)
);

CREATE TABLE IF NOT EXISTS ARQUIVOS (
    ID UUID PRIMARY KEY,
    DATA_GERACAO_INICIAL TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATA_GERACAO_FINAL TIMESTAMP,
    NOME_ARQUIVO VARCHAR(255) NOT NULL,
    DIRETORIO_ARQUIVO TEXT NOT NULL,
    OBSERVACAO TEXT,
    STATUS VARCHAR(255) NOT NULL DEFAULT 'EM_PROCESSAMENTO'
);